#spring.application.name=hello-service
##eureka.client.register-with-eureka=true
##eureka.client.serviceUrl.defaultZone=http://10.10.10.2:11111/eureka/,http://10.10.10.2:11112/eureka/
#
#server.port=8081
#
#grpc.client.localGrpcServer.host=localhost
#grpc.client.localGrpcServer.port=9090
#grpc.server.name=localGrpcServer
#grpc.server.port=9898
#grpc.server.address=localhost
server:
  port: 8089
spring:
  application:
    name: local-grpc-client
grpc:
  client:
    local-grpc-server:
      host:
        - 127.0.0.1
      port:
        - 9898
      enableKeepAlive: true
      keepAliveWithoutCalls: true